sonar.host.url=http://localhost:9000
sonar.login=sqa_d334a17310d2508e68dd7e1a2a4a1bdd098eddee
sonar.projectKey=sonarq-app
sonar.projectName=SonarQ Project
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8