sonar.host.url=http://localhost:9000
sonar.token=sqa_4a993f54ac9984276925aa6d87ec3a89015482ff
sonar.projectKey=sonarq
sonar.projectName=Calculator
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
